[project]
name = "project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vivek Vaidya", email = "vivekv4idya@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=3.26.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.4",
    "streamlit>=1.65.0",
]

[project.scripts]
project2 = "project2:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
